name: Archiving data for hour

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Binary
        run: ./crous_assistant_collector
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RUST_LOG: info
