name: Archiving data for hour

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
    creating-archive:
        permissions:
          contents: write
        uses: ./.github/workflows/reusable-archiving.yml
        with:
          ARCHIVE_MODE: HOUR
          deploy: true
        secrets:
          MAIL : ${{ secrets.TEST_MAIL }}
          PASSWORD : ${{ secrets.TEST_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}

    rerun-failed-jobs:
      runs-on: ubuntu-latest
      needs: creating-archive
      if: failure()
      steps:
        - name: Checkout
          uses:  actions/checkout@v4
        - name: Rerun failed jobs in the current workflow
          env: 
            GH_TOKEN: ${{ secrets.RERUN_TOKEN }}
          run: gh run rerun ${{ github.run_id }} --failed --repo ${{ github.repository }}


          

    