name: Archiving data for hour

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Binary
        run: ./crous_assistant_collector
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RUST_LOG: info
