name: Archiving data for hour

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Binary
        uses: actions/cache@v3
        with:
          path: ./binary/crous_assistant_collector
          key: ${{ runner.os }}-crous_assistant_collector-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-crous_assistant_collector-

      - name: Check if Binary Exists
        run: |
          if [ ! -f ./binary/crous_assistant_collector ]; then
            echo "Binary not found in cache. Exiting."
            exit 1
          fi

      - name: Make Binary Executable
        run: chmod +x ./binary/crous_assistant_collector

      - name: Execute Binary
        run: ./binary/crous_assistant_collector
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RUST_LOG: info
