name: Archiving data for day summary

on:
  schedule:
    - cron: '40 23 * * *'
  workflow_dispatch:
    inputs:
      specific-date:
        description: 'Specific date to archive'
        required: true
        default: '2024-01-01'

jobs:
    creating-archive-schedule:
      permissions:
        contents: write
      if: github.event_name == 'schedule'
      uses: ./.github/workflows/reusable-archiving.yml
      with:
        ARCHIVE_MODE: DAY_SUM_UP
        LINK_TO_DATA: https://mathieusoysal.github.io/CROUS-assistant-Collector/v2
        deploy: true
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}

    creating-archive-manual:
      permissions:
        contents: write
      if: github.event_name == 'workflow_dispatch'
      uses: ./.github/workflows/reusable-archiving.yml
      with:
        SPECIFIC_DAY: ${{ github.event.inputs.specific-date }}
        ARCHIVE_MODE: DAY_SUM_UP
        LINK_TO_DATA: https://mathieusoysal.github.io/CROUS-assistant-Collector/v2
        deploy: true
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}


          

    