name: Adding bin to cache

on:
    push:
        branches:
          - main 
    schedule:
        - cron: '0 0 1 */2 *'
    workflow_dispatch:

jobs:

    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Set up Rust
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              override: true
              components: clippy  # Optional, add components as needed

          - name: Cache Cargo Build
            id: cargo-cache
            uses: actions/cache@v3
            with:
              path: target/release
              key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
              restore-keys: |
                ${{ runner.os }}-cargo-build-

          - name: Build Release Binary
            run: cargo build --release

          - name: Cache Binary
            if: success() && steps.cargo-cache.outputs.cache-hit != 'true'
            uses: actions/cache@v3
            with:
              path: target/release/crous_assistant_collector
              key: ${{ runner.os }}-crous_assistant_collector-${{ github.sha }}
              restore-keys: |
                ${{ runner.os }}-crous_assistant_collector-
