name: Integration Tests

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

jobs:
    unit-test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Run tests
        run: mvn test
        env:
          SPECIFIC_DAY: "2024-01-03"
          ARCHIVE_MODE: HOUR
          TEST_MAIL : ${{ secrets.TEST_MAIL }}
          TEST_PASSWORD : ${{ secrets.TEST_PASSWORD }}

    creating-archive-with-connection:
      needs: unit-test
      uses: ./.github/workflows/reusable-archiving.yml
      with:
        ARCHIVE_MODE: HOUR
      secrets:
        MAIL : ${{ secrets.TEST_MAIL }}
        PASSWORD : ${{ secrets.TEST_PASSWORD }}

    creating-archive-day-sum-up:
      needs: unit-test
      uses: ./.github/workflows/reusable-archiving.yml
      with:
        ARCHIVE_MODE: DAY_SUM_UP
        SPECIFIC_DAY: "2024-01-03"
        LINK_TO_DATA: https://mathieusoysal.github.io/CROUS-assistant-Collector/v1/logements-crous/available

    creating-archive-all-logement:
      needs: unit-test
      uses: ./.github/workflows/reusable-archiving.yml
      with:
        ARCHIVE_MODE: ALL_LOGEMENTS
        SPECIFIC_DAY: "2024-01-03"
        LINK_TO_DATA: https://mathieusoysal.github.io/CROUS-assistant-Collector/v1/logements-crous/available