name: Release
on:
    release:
      types:
        - created

jobs:

  tests:
    uses: ./.github/workflows/Integration-test.yml
    secrets: inherit

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Run tests
        run: mvn clean install -D skipTests --no-transfer-progress
        env:
          MAIL : ${{ secrets.TEST_MAIL }}
          PASSWORD : ${{ secrets.TEST_PASSWORD }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/logement-crous-1.0.jar

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: downcase
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}
  
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
  
      - name: Build JIB container and publish to GitHub Packages
        run: |
          mvn package com.google.cloud.tools:jib-maven-plugin:3.4.0:build \
          -Djib.from.image=mcr.microsoft.com/playwright/java:v1.41.1-jammy \
          -Djib.to.image=ghcr.io/${{ steps.downcase.outputs.lowercase }}:latest \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
        env:
          TEST_MAIL : ${{ secrets.TEST_MAIL }}
          TEST_PASSWORD : ${{ secrets.TEST_PASSWORD }}
