name: Archiving data with reusable workflow

on:
  workflow_call:
    inputs:
        ARCHIVE_MODE:
            description: 'The mode of archiving'
            required: true
            type: string
            default: 'HOUR'
        LINK_TO_DATA:
            description: 'The link to the data to archive'
            required: false
            type: string
            default: 'https://mathieusoysal.github.io/CROUS-assistant-Collector/v1/logements-crous/available'
        SPECIFIC_DAY:
            description: 'The day to archive, day is used olny if ARCHIVE_MODE is DAY'
            required: false
            type: string
            default: ''
        deploy:
            description: 'Deploy the archive to github pages'
            required: false
            type: boolean
            default: false
        target-folder:
            description: 'The target folder to deploy the archive to github pages'
            required: false
            type: string
            default: 'v1/logements-crous'
      
    secrets:
        MAIL:
            description: 'The mail to send the archive to hour, mail is used olny if ARCHIVE_MODE is HOUR'
        PASSWORD:
            description: 'The password of the mail to send the archive to hour, password is used olny if ARCHIVE_MODE is HOUR'
        token:
            description: 'The token to deploy the archive to github pages'

jobs:
    creating-archive:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        - name: Install Playwright
          run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

        - name: set specific day when input is not empty
          if: inputs.SPECIFIC_DAY != ''
          run: echo "SPECIFIC_DAY=${{ inputs.SPECIFIC_DAY }}" >> $GITHUB_ENV

        - name: archive
          run: |
            (echo "===== Maven Deploy Attempt: 1 ====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java) || \
            (echo "===== Maven Deploy Attempt: 2 ====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java) || \
            (echo "===== Maven Deploy Attempt: 3 ====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java) || \
            (echo "==== Maven Deploy Step Failed ====" && exit 1)
          env:
            LINK_TO_DATA: ${{ inputs.LINK_TO_DATA }}
            ARCHIVE_MODE: ${{ inputs.ARCHIVE_MODE }}
            MAIL: ${{ secrets.MAIL }}
            PASSWORD: ${{ secrets.PASSWORD }}
        - name: Deploy to Github Pages
          if: inputs.deploy == true
          uses: JamesIves/github-pages-deploy-action@v4.4.3
          with:
            token: ${{ secrets.token }}
            clean: false
            branch: api
            folder: archive
            target-folder: ${{ inputs.target-folder }}